players = ["Abbie", "Brandon"]

trophy_names = [
    "Mushroom Cup",
    "Flower Cup",
    "Star Cup",
    "Egg Cup",
    "Special Cup",
    "Crossing Cup",
    "Shell Cup",
    "Banana Cup",
    "Leaf Cup",
    "Lightning Cup",
    "Triforce Cup",
    "Bell Cup",
]

carts = [
    "Circuit Special",
    "City Tripper",
    "Comet",
    "Sneeker",
    "Splat Buggy",
    "Standard ATV",
    "Standard Bike",
    "Standard Kart",
    "Steel Driver",
    "Streetle",
    "300 SL Roadster",
    "B Dasher",
    "Badwagon",
    "Biddybuggy",
    "Blue Falcon",
    "Bone Rattler",
    "Cat Cruiser",
    "Flame Rider",
    "GLA",
    "Gold Standard",
    "Inkstriker",
    "Jet Bike",
    "Koopa Clown",
    "Landship",
    "Mach 8",
    "Master Cycle",
    "Mr. Scooty",
    "P-Wing",
    "Pipe Frame",
    "Prancer",
    "Sport Bike",
    "Sports Coupe",
    "Tanooki Kart",
    "Teddy Buggy",
    "The Duke",
    "Tri-Speeder",
    "Varmint",
    "W 25 Silver Arrow",
    "Wild Wiggler",
    "Yoshi Bike",
]

wheels = [
    "Monster",
    "Off-Road",
    "Roller",
    "Slim",
    "Sponge",
    "Standard",
    "Azure Roller",
    "Blue Standard",
    "Button",
    "Crimson Slim",
    "Cushion",
    "Cyber Slick",
    "GLA Tires",
    "Gold Tires",
    "Hot Monster",
    "Leaf Tires",
    "Metal",
    "Retro Off-Road",
    "Slick",
    "Triforce Tires",
    "Wood",
]

gliders = [
    "Parachute",
    "Parafoil",
    "Plane Glider",
    "Super Glider",
    "Bowser Kite",
    "Cloud Glider",
    "Flower Glider",
    "Gold Glider",
    "Hylian Kite",
    "MKTV Parafoil",
    "Paper Glider",
    "Peach Parasol",
    "Waddle Wing",
    "Wario Wing",
]

characters = [
    "Mario",
    "Luigi",
    "Peach",
    "Daisy",
    "Yoshi",
    "Toad",
    "Toadette",
    "Koopa Troopa",
    "Bowser",
    "Donkey Kong",
    "Wario",
    "Waluigi",
    "Rosalina",
    "Metal Mario",
    "Pink Gold Peach",
    "Lakitu",
    "Shy Guy",
    "Baby Mario",
    "Baby Luigi",
    "Baby Peach",
    "Baby Daisy",
    "Baby Rosalina",
    "Larry",
    "Lemmy",
    "Wendy",
    "Ludwig",
    "Iggy",
    "Roy",
    "Morton",
    "Villager (Boy)",
    "Villager (Girl)",
    "Isabelle",
    "Dry Bowser",
    "Tanooki Mario",
    "Cat Peach",
    "Link",
    "King Boo",
    "Dry Bones",
    "Bowser Jr.",
    "Inkling Girl",
    "Inkling Boy",
    "Gold Mario",
]
